samples_folder: ./fastq
output_folder: ./output
num_threads: 8
min_length: 16
bowtie_path: ./mirge_library/bowtie-1.3.0-macos-x86_64
samtools_path: ./mirge_library/samtools/1.20/bin
mirge_lib_path: ./mirge_library
bam_output: TRUE
n_cpus: 8
# Do you want to install tools? (bowtie, samtools, mirge, organism library)
install_tools: False

species: mouse